export const START_GAME = 'start_game'
export const END_GAME = 'end_game'
export const RESET_GAME = 'reset_game'
export const NEXT_LEVEL = 'next_level'
export const GUESS_COLOR = 'guess_color'
export const SEQUENCE_ON = 'sequence_on'
export const SEQUENCE_OFF = 'sequence_off'
export const ACTIVE_PAD = 'active_pad'